#!/usr/bin/env bash
# Secure copy from the client to the server
if ["$#" -lt 4]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	FILE_PATH="$1";
	SERVER_IP="$2";
	USERNAME="$3";
	SSH_KEY_PATH="$4";
    scp -i "$4" -o "StrictHostKeyChecking=no" "$1" "$3@$2":~/;
fi
