#!/usr/bin/env bash
# install nginx

sudo apt update && sudo apt install nginx -y
sudo echo "server { listen 80; 513329-web-01 100.26.17.150;}" > /etc/nginx/ngnix.conf
sudo echo "Hello, World!" > /var/www/html/index.nginx-debian.html
sudo service start nginx
