#!/usr/bin/env bash
#a Bash script that stops 4-to_infinity_and_beyond process.
#Requirements:
#   You cannot use kill or killall
pid=$(ps aux | grep 4-to_infinity_and_beyond | grep -v grep | awk '{print $2}')
pkill "$pid"

