#!/usr/bin/env bash
# Displays 'Best School' every time, in the 9th iteration, displays 'Hi' as well.

hi="Hi"
school="Best School"

for i in {1..10}
do
	echo $school
	if [ $i -eq 9 ]
	then
		echo $hi
	fi
done
