#!/usr/bin/env bash
#Displays 'Best School' every time, in the 9th iteration, displays 'Hi' as well.

hi="Hi"
school="Best School"
i=0
while ((i<10))
do
	if [ $i -eq 9 ]
	then
		echo $hi
	fi
	echo $school
	((i++))
done
