#!/usr/bin/env bash
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
#displays Best School for the other iterations
# Requirements:
#    You must use the while loop (for and until are forbidden)
#    You must use the if, elif and else statements
i=0
schl="Best School"
bdlck="bad luck"
gdlck="good luck"
while [[ $i -ne 10 ]]; do
	((i++))
	if [[ $i -eq 4 ]]; then
		echo $bdlck
	fi

	if [[ $i -eq 8 ]]; then
		echo $gdlck
	fi

	if [[ $i -ne 4 && $i -ne 8 ]]; then
		echo $schl
	fi
done
