#!/usr/bin/env bash
# Write a Bash script that displays:
#    The content of the current directory
#    In a list format
#   Where only the part of the name after the first dash is displayed

filenames=$(ls -1 -b .)
for filename in $filenames; do
	new_filename=$(cut -d '-' -f 2- <<< "$filename")
	echo $new_filename
done
